FROM intersystems/iam:2.3.3.2-1

USER root
COPY ./plugins /custom/plugins

RUN cd /custom/plugins/kong-plugin-helloworld && luarocks make
RUN cd /custom/plugins/kong-plugin-jwt-crafter && luarocks make

#USER kong

